---
title: '‘Liquidity’, a keyword in the history of capitalism: Introduction'
author: Michael Beggs
date: '2019-01-28'
slug: liquidity-a-keyword-in-the-history-of-capitalism-introduction
categories: []
tags: [liquidity]
excerpt: "Economist: Well, the Committee doesn’t actually define liquidity anywhere, Socrates…"
---
>_liquidity, n.: Econ._ The interchangeability of assets and money. `r tufte::margin_note("_Oxford English Dictionary_, 2 ed. (1989).")`

>You don’t anywhere come right out in the open and say what liquidity is. `r tufte::margin_note("Joan Robinson (1935) Letter to John Maynard Keynes.")`

>a highly complex phenomenon. Its concrete manifestation is powerfully affected by changes in financial institutions and practices, which have been occurring with extraordinary rapidity in recent decades. It calls for analysis both at the microeconomic and the macroeconomic level, with unusually strong dangers of committing fallacies of composition.`r tufte::margin_note("A. B. Cramp (1987) 'Liquidity,' _New Palgrave Dictionary of Economics_.")`

>No formal definition is equivalent to any substantial definition except under very artificial assumptions… It is the ambiguity in the definition of liquidity preference which gives it the appearance to some of being at one and the same time useful, formally valid, and of very general application. It may with suitable chosen definitions be any two of these but never all three. `r tufte::margin_note("Max Millikan (1938) ‘The liquidity-preference theory of interest,’ _American Economic Review_, 28(2), p. 247.")`

>Socrates: Now tell me about ‘the liquidity position as a whole,’ on which I understand the Committee places great emphasis. How does the Committee define liquidity?

>Economist: Well, the Committee doesn’t actually define liquidity anywhere, Socrates… `r tufte::margin_note("W. T. Newlyn (1960) ‘The Radcliffe Report: a Socratic scrutiny,’ _Banker’s Magazine_.")`

‘Liquidity’—in its economic usages—is a very strange term, resisting definition. Sure, you can find  straightforward definitions, like the one in the _OED_—but there are too many, they give different meanings and still don’t cover all the ways the word has been used.

It’s not just that the meaning has changed over time. It has, of course, but at any point in time it has been marked by different uses. Not just different meanings in different contexts—that’s normal where words are concerned—but different meanings that seem to get thrown together in the same space. There were shared, stable meanings in certain subliteratures, but they bled into one another and caused confusion whenever literatures started to intermingle: say, when the ‘liquidity’ of a parliamentary banking enquiry met the ‘liquidity’ of macroeconomists. Even within the subliteratures, meanings proliferated. It is a word that easily throws off new usages that make intuitive sense given family resemblances between concepts. But over time the plant grows weird branches so that it no longer seems to be all one organism, and the conceptual pruning begins. But the cast-offs find soil somewhere else and keep growing, and sometimes someone rediscovers them and grafts them back on.

Scattered across the decades are a number odd pieces trying to sort out what ‘liquidity’ meant—I quote from a few above, from the 1930s through the 1980s. They are alike in one way: the writers conclude it is hard to define ‘liquidity’ in a satisfying way. There have been attempts to expunge it from the lexicon: [‘For an answer which cannot be expressed the question too cannot be expressed. _The riddle_ does not exist.’](http://www.bazzocchi.net/wittgenstein/tractatus/eng/index.htm)

But people clearly kept hearing the riddle nonetheless, because ‘liquidity’ always came back. (It fell out of favour in economics in the 1980s and 1990s, but came roaring back again with 2008 and all that. Cramp’s great entry on ‘liquidity’ from the first edition of the _New Palgrave_ was missing from the second, 2008, edition and restored for the third in 2018. Bank liquidity requirements were out of fashion for Basels I (1988) and II (2004), but back in time for Basel III (2010).)

**A difficult word**

>It was just a difficult word, a word I could think of as an example of the change which we were trying, in various ways, to understand.`r tufte::margin_note("Raymond Williams (2 ed., 1983) _Keywords: a vocabulary of culture and society_, p. 13.")`


The riddle of ‘liquidity’ is posed by the social relationships it refers to. It is tricky in part because what it refers to is difficult to understand, and in part because the relations it refers to are evolving all the time. My hunch is that ‘liquidity’ is one of those words Raymond Williams discussed in _Keywords_, whose evolution and problems tell us something about the evolution and problems of capitalism itself.

Williams wrote of

>a process quite central in the development of a language when, in certain words, tones and rhythms, meanings are offered, felt for, tested, confirmed, asserted, qualified, changed. In some situations this is a very slow process indeed; it needs the passage of centuries to show itself actively, by results, at anything like its full weight. In other situations the process can be rapid, especially in certain key areas.`r tufte::margin_note("Wililams (1983), p. 12.")`

‘Liquidity’ is one of these latter words. The story is largely a twentieth century one, though it continues to the present and has ancestor concepts stretching further back. Like Williams, I treat it as an indicator, a useful way in to understanding social change. The word both reflects that change and is part of the change—it has been used as part of attempts to pick out, describe, explain and intervene in real social relationships and processes:

>Of course the issues could not all be understood simply by analysis of the words. On the contrary, most of the social and intellectual issues, including both gradual developments and the most explicit controversies and conflicts, persisted within and beyond the linguistic analysis. Yet many of these issues, I found, could not really be thought through, and some of them, I believe, cannot even be focused unless we are conscious of the words as elements of the problems.`r tufte::margin_note("Williams (1983), pp. 15-16.")`

Where Williams was interested particularly in words which had passed from specialised meanings into common usage, I am interested in liquidity mainly as a technical term in economics and finance. I think that still fits the project as Williams described it, because economics and finance and their discourses are so important to the infrastructure of capitalism.

**Why is liquidity a keyword?**

I think the troublesomeness of ‘liquidity’ comes down especially to two things:

1. Liquidity crosses the state-economy divide. On the one hand, liquidity can be sustained through the strategic action of numerous self-interested agents. On the other hand, the landscape of liquidity is profoundly shaped by official activity. State agents can often foster the liquidity of particular instruments and institutions, but it is harder for them to withdraw liquidity when other agents are supporting it. Liquidity dynamics are challenging for one-sided state- and market-centred understandings of money. Puzzling about liquidity in the literature is often connected to the evolution of the role of states within the capitalist financial system, and the evolution of that system itself.

2. Liquidity does not fit neatly into either micro- or macroeconomics, the two major approaches to understanding capitalism within the discipline of economics. That is the point Cramp makes in the excellent Palgrave entry quoted up the top there. There are, as Cramp puts it, ‘unusually strong dangers of committing fallacies of composition’. Further, it involves issues of time and uncertainty that have made it difficult to formalise in ways that are both realistic and rigorous in the sense recognised by modern economics. ‘Liquidity’ appears in plenty of models, but it has tended to escape abstraction.